export const getQueryPromoList = `
query GetPromoList {
    getPromoList {
        status
        code
        message
        requestUuid
        promoListData {
            id
            title
            icon
            imageUrl
            description
            terms
            accessible
            disabled
            interaction
            status
            available
            schedule {
                setNumber
                totalItems
                pageNumber
                pageSize
                schedulerId
                items {
                    status
                    expirationDate
                    campaignId
                    startDate
                    schedulerId
                    knownReward {
                        externalId
                        rewardCode
                        rewardPosCode
                        allowSelfRedeem
                        issuedDate
                        redeemedOn
                        patronName
                        rewardStates
                        rewardRedemptionInfo
                        cost
                        costType
                        ucWebhookType
                        deliveryOptions
                        hasOnScreenDeliveryOption
                        name
                        htmlName
                        imageUrl
                        description
                        termsAndConditions
                        startDate
                        expirationDate
                        startDateExt
                        endDateExt
                        rewardStateExt
                    }
                }
            }
            reward {
                externalId
                rewardCode
                rewardPosCode
                allowSelfRedeem
                issuedDate
                redeemedOn
                patronName
                rewardStates
                rewardRedemptionInfo
                cost
                costType
                ucWebhookType
                deliveryOptions
                hasOnScreenDeliveryOption
                name
                htmlName
                imageUrl
                description
                termsAndConditions
                startDate
                expirationDate
                startDateExt
                endDateExt
                rewardStateExt
            }
            raw {
                id
                title
                imageUrl
                description
                termsAndConditions
                isAccessible
                isDisabled
                isDisabledMessage
                isDisabledType
                hasInteractions
                hasInteractionOnRewardsLevel
                sequence
                status
                externalCampaignId
                knownReward {
                    externalId
                    rewardCode
                    rewardPosCode
                    allowSelfRedeem
                    issuedDate
                    redeemedOn
                    patronName
                    rewardStates
                    rewardRedemptionInfo
                    cost
                    costType
                    ucWebhookType
                    deliveryOptions
                    hasOnScreenDeliveryOption
                    name
                    htmlName
                    imageUrl
                    description
                    termsAndConditions
                    startDate
                    expirationDate
                    startDateExt
                    endDateExt
                    rewardStateExt
                }
                schedule {
                    setNumber
                    totalItems
                    pageNumber
                    pageSize
                    schedulerId
                    items {
                        campaignId
                        status
                        startDate
                        expirationDate
                        schedulerId
                        knownReward {
                            externalId
                            rewardCode
                            rewardPosCode
                            allowSelfRedeem
                            issuedDate
                            redeemedOn
                            patronName
                            rewardStates
                            rewardRedemptionInfo
                            cost
                            costType
                            ucWebhookType
                            deliveryOptions
                            hasOnScreenDeliveryOption
                            name
                            htmlName
                            imageUrl
                            description
                            termsAndConditions
                            startDate
                            expirationDate
                            startDateExt
                            endDateExt
                            rewardStateExt
                        }
                    }
                }
                accessibilities {
                    value
                }
            }
        }
    }
}

`;

export const getQueryPromoListWithExtraField = `
query GetPromoList {
    getPromoList {
        status
        code
        message
        requestUuid
        unexpectedField
        promoListData {
            id
            title
            icon
            imageUrl
            description
            terms
            accessible
            disabled
            interaction
            status
            available
            schedule {
                setNumber
                totalItems
                pageNumber
                pageSize
                schedulerId
                items {
                    status
                    expirationDate
                    campaignId
                    startDate
                    schedulerId
                    knownReward {
                        externalId
                        rewardCode
                        rewardPosCode
                        allowSelfRedeem
                        issuedDate
                        redeemedOn
                        patronName
                        rewardStates
                        rewardRedemptionInfo
                        cost
                        costType
                        ucWebhookType
                        deliveryOptions
                        hasOnScreenDeliveryOption
                        name
                        htmlName
                        imageUrl
                        description
                        termsAndConditions
                        startDate
                        expirationDate
                        startDateExt
                        endDateExt
                        rewardStateExt
                    }
                }
            }
            reward {
                externalId
                rewardCode
                rewardPosCode
                allowSelfRedeem
                issuedDate
                redeemedOn
                patronName
                rewardStates
                rewardRedemptionInfo
                cost
                costType
                ucWebhookType
                deliveryOptions
                hasOnScreenDeliveryOption
                name
                htmlName
                imageUrl
                description
                termsAndConditions
                startDate
                expirationDate
                startDateExt
                endDateExt
                rewardStateExt
            }
            raw {
                id
                title
                imageUrl
                description
                termsAndConditions
                isAccessible
                isDisabled
                isDisabledMessage
                isDisabledType
                hasInteractions
                hasInteractionOnRewardsLevel
                sequence
                status
                externalCampaignId
                knownReward {
                    externalId
                    rewardCode
                    rewardPosCode
                    allowSelfRedeem
                    issuedDate
                    redeemedOn
                    patronName
                    rewardStates
                    rewardRedemptionInfo
                    cost
                    costType
                    ucWebhookType
                    deliveryOptions
                    hasOnScreenDeliveryOption
                    name
                    htmlName
                    imageUrl
                    description
                    termsAndConditions
                    startDate
                    expirationDate
                    startDateExt
                    endDateExt
                    rewardStateExt
                }
                schedule {
                    setNumber
                    totalItems
                    pageNumber
                    pageSize
                    schedulerId
                    items {
                        campaignId
                        status
                        startDate
                        expirationDate
                        schedulerId
                        knownReward {
                            externalId
                            rewardCode
                            rewardPosCode
                            allowSelfRedeem
                            issuedDate
                            redeemedOn
                            patronName
                            rewardStates
                            rewardRedemptionInfo
                            cost
                            costType
                            ucWebhookType
                            deliveryOptions
                            hasOnScreenDeliveryOption
                            name
                            htmlName
                            imageUrl
                            description
                            termsAndConditions
                            startDate
                            expirationDate
                            startDateExt
                            endDateExt
                            rewardStateExt
                        }
                    }
                }
                accessibilities {
                    value
                }
            }
        }
    }
}

`;

export const partialGetQueryPromoList = `
query GetPromoList {
    getPromoList {
        message
        requestUuid
        promoListData {
            id
            title
            icon
            imageUrl
            description
            terms
            accessible
            disabled
            interaction
            status
            available
            schedule {
                setNumber
                totalItems
                pageNumber
                pageSize
                schedulerId
                items {
                    status
                    expirationDate
                    campaignId
                    startDate
                    schedulerId
                    knownReward {
                        externalId
                        rewardCode
                        rewardPosCode
                        allowSelfRedeem
                        issuedDate
                        redeemedOn
                        patronName
                        rewardStates
                        rewardRedemptionInfo
                        cost
                        costType
                        ucWebhookType
                        deliveryOptions
                        hasOnScreenDeliveryOption
                        name
                        htmlName
                        imageUrl
                        description
                        termsAndConditions
                        startDate
                        expirationDate
                        startDateExt
                        endDateExt
                        rewardStateExt
                    }
                }
            }
            reward {
                externalId
                rewardCode
                rewardPosCode
                allowSelfRedeem
                issuedDate
                redeemedOn
                patronName
                rewardStates
                rewardRedemptionInfo
                cost
                costType
                ucWebhookType
                deliveryOptions
                hasOnScreenDeliveryOption
                name
                htmlName
                imageUrl
                description
                termsAndConditions
                startDate
                expirationDate
                startDateExt
                endDateExt
                rewardStateExt
            }
            raw {
                id
                title
                imageUrl
                description
                termsAndConditions
                isAccessible
                isDisabled
                isDisabledMessage
                isDisabledType
                hasInteractions
                hasInteractionOnRewardsLevel
                sequence
                status
                externalCampaignId
                knownReward {
                    externalId
                    rewardCode
                    rewardPosCode
                    allowSelfRedeem
                    issuedDate
                    redeemedOn
                    patronName
                    rewardStates
                    rewardRedemptionInfo
                    cost
                    costType
                    ucWebhookType
                    deliveryOptions
                    hasOnScreenDeliveryOption
                    name
                    htmlName
                    imageUrl
                    description
                    termsAndConditions
                    startDate
                    expirationDate
                    startDateExt
                    endDateExt
                    rewardStateExt
                }
                schedule {
                    setNumber
                    totalItems
                    pageNumber
                    pageSize
                    schedulerId
                    items {
                        campaignId
                        status
                        startDate
                        expirationDate
                        schedulerId
                        knownReward {
                            externalId
                            rewardCode
                            rewardPosCode
                            allowSelfRedeem
                            issuedDate
                            redeemedOn
                            patronName
                            rewardStates
                            rewardRedemptionInfo
                            cost
                            costType
                            ucWebhookType
                            deliveryOptions
                            hasOnScreenDeliveryOption
                            name
                            htmlName
                            imageUrl
                            description
                            termsAndConditions
                            startDate
                            expirationDate
                            startDateExt
                            endDateExt
                            rewardStateExt
                        }
                    }
                }
            }
        }
    }
}

`;
